### PR TITLE
docker-compose.yml OMERO.server websockets

### PR DESCRIPTION
**Pull request by manics**
Requires:
- https://github.com/openmicroscopy/openmicroscopy/pull/5927
- https://github.com/openmicroscopy/openmicroscopy/pull/5997
- https://github.com/openmicroscopy/openmicroscopy/pull/5998

### CODE REVIEW

**Comment by joshmoore** [comment]
Re-opening to trigger travis.

**Comment by joshmoore** [comment]
Nice. travis is green with west-ci build.

**Comment by joshmoore** [comment]
Waiting on the next tag for changing source and re-testing. cc: @jburel

**Comment by joshmoore** [comment]
Green. Merging, unless we want to test the `5.5` URL alias via this PR.

cc: @jburel @sbesson

**Comment by sbesson** [comment]
Looks good. I assume eventually the URLs will download the latest server and be tested via some cron mechanism. Unless there is value in testing the 5.5.0-rc1, happy to see merged.

**Comment by joshmoore** [comment]
Merging.

@manics : I don't know what the SERVER build argument was for.

**Comment by manics** [comment]
It was inadvertently leftover from testing

**Pull request merged**
