### PR TITLE
Pin pytest==3.3.2

### PR DESCRIPTION
**Pull request by joshmoore**
Attempted fix for the failure in https://travis-ci.org/ome/docker-example-omero-websockets/builds/566896548

### CODE REVIEW

**Comment by joshmoore** [comment]
cf. https://github.com/ome/omero-mapr/pull/31/files#r168171248

**Comment by manics** [comment]
The last working build used 4.6.0: https://travis-ci.org/ome/docker-example-omero-websockets/builds/540346128

https://github.com/ome/omero-mapr/pull/31/files#r168171248 doesn't explain why 3.3.2 was chosen

**Comment by joshmoore** [comment]
But 3.2 *is* working. If you'd prefer an alternative, feel free to close this and open up 4.6 PRs where necessary. Only caveat is that _hopefully_ we can soon get rid of all this pinning!

**Comment by joshmoore** [comment]
Green without the pin!

**Comment by joshmoore** [comment]
Since #4 moves to Python 3, closing

**Pull request closed without merging**
