### PR TITLE
Simplify ice-websocket self-signed certs

### PR DESCRIPTION
**Pull request by manics**
This replaces the zeroc-icecertutils python utility with `openssl` commands for generating self-signed certificates. This makes it easier to generate internal certificates on a production server since no additional depencies are needed.

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [DOCKER-merge#884](https://ci.openmicroscopy.org/job/DOCKER-merge/884/). See the [console output](https://ci.openmicroscopy.org/job/DOCKER-merge/884/consoleText) for more details.
Possible conflicts:
  - PR #2 joshmoore 'Pin pytest==3.3.2'
    - test/Dockerfile

~~--conflicts~~ Conflict resolved in build [DOCKER-merge#1013](https://ci.openmicroscopy.org/job/DOCKER-merge/1013/). See the [console output](https://ci.openmicroscopy.org/job/DOCKER-merge/1013/consoleText) for more details.

**Comment by joshmoore** [comment]
@manics : would you rather integrate #4 here or put this on hold and get #4 in?

**Comment by joshmoore** [comment]
@manics : ping

**Comment by manics** [comment]
I'll include it in https://github.com/ome/docker-example-omero-websockets/pull/4 once the Docker `latest` images are released, doesn't seem much point in setting it to `5.6` and changing it back to `latest`. Most of the contents of the Dockerfile are due to this repo predating the first web-sockets release so can be deleted.

**Comment by joshmoore** [comment]
Closing this PR then to also let #5 in.

**Pull request closed without merging**
